#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions

touch omesh.foam

runApplication blockMesh

runApplication setSet -batch system/pointSetBatch

runApplication optiMesh

