#!/bin/bash
cd ${0%/*}

wmake libso liboptiMesh 2>&1 | tee log.liboptiMesh
wmake libso libextraSets 2>&1 | tee log.libextraSets

if [ -d $FOAM_USER_LIBBIN ]
then
  cp -t $FOAM_USER_LIBBIN/ ./bashTools/bashTools
fi
